# action.yaml
name: "Github Secrets into AWS Secrets Manager"
description: "Inject Secrets from a Github Repository into a AWS Secrets Manager's entry (as a json)"
branding:
  icon: 'upload-cloud'  
  color: 'green'
runs:
  using: "docker"
  image: "Dockerfile"